@startuml
object ticTacticalToe
object ticTacticalToe.urls
object ticTacticalToe.views
object ticTacticalToe.routing
object ticTacticalToe.consumers
object Accounts
object Accounts.models
object Accounts.urls
object Accounts.views
object Game
object Game.urls
object Game.models
object Game.views
object Stats
object Stats.urls
object Stats.views
object models.User
object models.Game
object models.GameSquare
object models.GameLog

ticTacticalToe <|-- ticTacticalToe.urls
ticTacticalToe <|-- ticTacticalToe.views
ticTacticalToe.urls <|-- Accounts.urls
ticTacticalToe.urls <|-- Game.urls
ticTacticalToe.urls <|-- Stats.urls
ticTacticalToe <|-- ticTacticalToe.consumers
ticTacticalToe <|-- ticTacticalToe.routing
ticTacticalToe <|-- Accounts
ticTacticalToe <|-- Game
ticTacticalToe <|-- Stats
Accounts <|-- Accounts.urls
Accounts <|-- Accounts.views
Accounts <|-- Accounts.models
Accounts.models <|-- models.User
Game <|-- Game.urls
Game <|-- Game.views
Game <|-- Game.models
Stats <|-- Stats.urls
Stats <|-- Stats.views
Game.models <|-- models.Game
Game.models <|-- models.GameSquare
Game.models <|-- models.GameLog
@enduml
