@startuml
object ticTacticalToe
object ticTacticalToe.urls
object ticTacticalToe.views
object ticTacticalToe.routing
object ticTacticalToe.consumers
object Accounts
object Accounts.models
object Accounts.urls
object Accounts.views
object Game
object Game.urls
object Game.models
object Game.views
object models.User
object models.Game
object models.GameSquare
object models.GameLog

ticTacticalToe <|-- ticTacticalToe.urls
ticTacticalToe <|-- ticTacticalToe.views
ticTacticalToe.views <|-- Accounts.views
ticTacticalToe.views <|-- Game.views
ticTacticalToe <|-- ticTacticalToe.consumers
ticTacticalToe <|-- ticTacticalToe.routing
ticTacticalToe <|-- Accounts
ticTacticalToe <|-- Game
Accounts <|-- Accounts.urls
Accounts <|-- Accounts.views
Accounts <|-- Accounts.models
Accounts.models <|-- models.User
Game <|-- Game.urls
Game <|-- Game.views
Game <|-- Game.models
Game.models <|-- models.Game
Game.models <|-- models.GameSquare
Game.models <|-- models.GameLog
@enduml
